// @ts-nocheck

const ENV = process.env.REACT_APP_ENV || process.env.NODE_ENV
const IS_DEV = ENV === 'development' || ENV === 'dev'
const IS_STG = ENV === 'stg' || ENV === 'staging'
const IS_PROD = ENV === 'production' || ENV === 'prod'

const IS_FIREBASE_CLI = process.env.IS_FIREBASE_CLI === 'true';
const FUNCTIONS_EMULATOR = process.env.FUNCTIONS_EMULATOR === 'true';
const FIREBASE_DEBUG_MODE = process.env.FIREBASE_DEBUG_MODE === 'true';
const FIREBASE_AUTH_EMULATOR_HOST = process.env.FIREBASE_AUTH_EMULATOR_HOST;
const FIRESTORE_EMULATOR_HOST = process.env.FIRESTORE_EMULATOR_HOST;
const FIREBASE_DATABASE_EMULATOR_HOST = process.env.FIREBASE_DATABASE_EMULATOR_HOST;
const FIREBASE_STORAGE_EMULATOR_HOST = process.env.FIREBASE_STORAGE_EMULATOR_HOST;


export {
    IS_DEV,
    IS_STG,
    IS_PROD,
    ENV,
    IS_FIREBASE_CLI,
    FUNCTIONS_EMULATOR,
    FIREBASE_DEBUG_MODE,
    FIREBASE_AUTH_EMULATOR_HOST,
    FIRESTORE_EMULATOR_HOST,
    FIREBASE_DATABASE_EMULATOR_HOST,
    FIREBASE_STORAGE_EMULATOR_HOST
}

