declare const ENV: any;
declare const IS_DEV: boolean;
declare const IS_STG: boolean;
declare const IS_PROD: boolean;
declare const IS_FIREBASE_CLI: boolean;
declare const FUNCTIONS_EMULATOR: boolean;
declare const FIREBASE_DEBUG_MODE: boolean;
declare const FIREBASE_AUTH_EMULATOR_HOST: any;
declare const FIRESTORE_EMULATOR_HOST: any;
declare const FIREBASE_DATABASE_EMULATOR_HOST: any;
declare const FIREBASE_STORAGE_EMULATOR_HOST: any;
declare const GCLOUD_PROJECT: any;
declare const FIREBASE_CONFIG: any;
declare const GOOGLE_APPLICATION_CREDENTIALS: any;
declare const getFirebaseConfig: () => any;
declare const getEmulatorsConfig: () => any;
declare const setFirebaseEmulators: (info: boolean) => void;
export { IS_DEV, IS_STG, IS_PROD, ENV, IS_FIREBASE_CLI, FUNCTIONS_EMULATOR, FIREBASE_DEBUG_MODE, FIREBASE_AUTH_EMULATOR_HOST, FIRESTORE_EMULATOR_HOST, FIREBASE_DATABASE_EMULATOR_HOST, FIREBASE_STORAGE_EMULATOR_HOST, GCLOUD_PROJECT, FIREBASE_CONFIG, GOOGLE_APPLICATION_CREDENTIALS, getEmulatorsConfig, getFirebaseConfig, setFirebaseEmulators, };
